import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import "../styles/globals.css"
import Navbar from "@/components/navbar"
import Head from "next/head"
import { cn } from "@/lib/utils"
import { Nunito_Sans as FontNunito } from "next/font/google"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
const fontNunito = FontNunito({
  subsets: ["latin"],
  variable: "--font-sans-latin",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased text-white",
          fontNunito.variable
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
